apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-1f34e411-d064-492d-8544-720ae5c6f186
  name: devfile-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-99-tenant/load-app-1f34e411-d064-492d-8544-720ae5c6f186/devfile-sample@sha256:502b96aeb3152c4046f9d9d138b3e8223d495ab8990621c65b0c3c85ac572896
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
